### ISSUE TITLE
Suggestion on dealing with multiple items with the same id?

### ISSUE THREAD

**Issue by brynnb** [Doist/todoist-api#14]
If you have a recurring task, all instances have the same ID. This means if you want to track the number of times it has been completed, you would have to look at some other field to make it unique. The only thing that would really work is the created_at field, but then the issue is that this is not available when getting completed items. This means if I originally retrieved and saved the item when it was complete but not archived, I would have no way to match it up to itself once it's been archived. 

The only way I can imagine around this is using the API to uncomplete the item, see its creation date, then re-mark it as complete, pull in completed items again, and assume the new one that's been added with the completion date relatively close to now() is the one I just marked as complete. This is a terrible solution.

Am I missing some other way to do this?

**Comment by eleftherios-c** [comment]
This is an unfortunate workaround to do what you want.  We are currently working on providing an events/activities log that will make it possible to keep track of such information, such as how many times an item has been completed.  We are currently working on it very actively and we plan to make it public soon

**Comment by lefcha** [comment]
The activity log has been released some time ago, and you can actually see all events related to your account, including tasks completed once or multiple times (recurring).

You can access the activity log through the API as described here:

https://developer.todoist.com/#activity
