### ISSUE TITLE
Mention that minute_offset parameter for reminder is enum, not an arbitrary Int

### ISSUE THREAD

**Issue by vpavkin** [Doist/todoist-api#17]
When I do the `reminder_add` request with for example `minute_offset = 40`, in the web UI I get reminder   with title `undefined before`. 
But everything works ok for `minute_offset` taken from the suggestion list. It should be mentioned in the API docs I think :)

**Comment by PotHix** [comment]
This is really old, but I can see it was solved a long time ago. I'm closing this, please re-open if there's something still missing. :+1:
