### ISSUE TITLE
Support for JSONP or CORS

### ISSUE THREAD

**Issue by odedhb** [Doist/todoist-api#18]
Am I missing something?

**Comment by imankulov** [comment]
You are not missing anything. There is no support for cross-origin requests currently. 

Coincidentally though, we are working to add CORS to the API, and we plan to release it, and to update the documentation accordingly, by the next week. I will keep you in touch.

**Comment by odedhb** [comment]
Great! Thanks

**Comment by odedhb** [comment]
Hi Roman, any updates?

**Comment by imankulov** [comment]
Hi! CORS support works already, and we also updated the documentation (new documentation will be available on http://developer.todoist.com/ soon). Feel free to explore it and to re-open the ticket (or to create a new one) if you feel like we missed something. Thanks!

**Comment by heidiv** [comment]
Hello! An access token seems to be required for the CORS preflight request, resulting in "Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource." 

```
curl -H "Origin: http://example.com" \
  -H "Access-Control-Request-Method: POST" \
  -H "Access-Control-Request-Headers: X-Requested-With" \
  -X OPTIONS --verbose \
  https://todoist.com/API/v7/sync
```

should give a "`Access-Control-Allow-Origin: *`" header, right?

https://www.w3.org/TR/cors/#preflight-request "Exclude credentials"

**Comment by daremon** [comment]
Hi @heidiv,

You are right, CORS preflight request don't get the correct headers back. We'll see what can be done about that. In the meantime, I guess the only option is trying not to trigger preflight requests.

**Comment by scottwittrock** [comment]
Hello @daremon, checking to see if there is any update on this? Trying to set up an integration, and when I send a request to https://todoist.com/oauth/access_token, i receive the same error as @heidiv. Anyone able to find a way around this?

**Comment by daremon** [comment]
Hi @scottwittrock 

For the time being the only solution is to make sure you make [simple requests](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Simple_requests).
