### ISSUE TITLE
Webhooks stopped working?

### ISSUE THREAD

**Issue by khurshid-alam** [Doist/todoist-api#19]
It seems since 26 oct, webhook stopped working. It is not sending any event to the url. I double checked that my url is working just fine.

![webhook](http://i.imgur.com/XuPhy8R.png)

The url is simple php script, for example

```php
$res = file_get_contents('php://input');
file_put_contents("td.log", $res."\n", FILE_APPEND);

echo "HTTP/1.1 200 OK";

http_response_code(200);
```

Why isn't it working?

**Comment by tplaner** [comment]
They have stopped working for our service rindle.com as well. Last Webhook we received was Thu, 27 Oct 2016 23:02:50 GMT.

**Comment by artyom** [comment]
Thank you for the report. This issue should now be resolved: no events are lost, they will all be delivered shortly.
