### ISSUE TITLE
Allow Get all completed items method for non-premium users for easy migration from other services.

### ISSUE THREAD

**Issue by khurshid-alam** [Doist/todoist-api#20]
I am shocked to see that "**Get all completed items**" (https://todoist.com/API/v7/completed/get_all) method from v7 api is not for normal users.

![todoist-get-completed](http://i.imgur.com/71i6rgW.png)

We, at Medo, encourage our employees to migrate to Todoist from other online services (Like Remember the milk). We use a simple python script to achieve that. But without any sort direct method to sync completed tasks for normal users, it, most times, ends up with duplicate and missing tasks. The other workarounds are not convenient at all.

So it would be nice if it can be used for normal users as well.

_Note: We do use Todoist Business Plan but only selected members are part of it._

Thanks.

**Comment by imankulov** [comment]
Hi @khurshid-alam. Unavailability of the `completed/get_all` is not an API issue, but rather a limitation of the free tariff plan. If you want to keep track of which tasks were completed, you an use the [activity API](https://developer.todoist.com/#activity) which provides similar functionality.

**Comment by khurshid-alam** [comment]
Thanks for your response. This is unfortunate, as activity api is again premium only feature.

**Comment by imankulov** [comment]
@khurshid-alam , yes you are right. Sorry, I overlooked this. Can you please describe your workflow in more details, or namely how the absence of access to completed tasks can end up with duplicate and missing tasks in your case. Maybe we can come up with acceptable alternative solution for you. Thanks!

**Comment by khurshid-alam** [comment]
Sorry for late reply.......

Usually we do not sync completed tasks which were closed even before sync engine sees it. But for failsafe even if we do, it's not more than 50 tasks....(we imported them under project under tags with tags and then completes them; of course timestamp would change but we don't care.

The problem arises because we don't know if users already synced before. If it's the very first time the sync is run, it's possible that the user already synced his tasks in some way (but we don't know that). Therefore, we attempt to induce those tasks relationships matching the titles. **However without getting a list of completed items** relationship between tasks loses its syncability property. The code is something like:

```python
        self.cancellation_point()
        meme = self.sync_engine.get_meme_from_local_id(tid)
        # First of all, the relationship is lost
        self.sync_engine.break_relationship(local_id=tid)
        if meme.get_origin() == "GTG":
            rtm_task.delete()
        else:
            self.datastore.request_task_deletion(tid)
```

2. Also the problem arises if users want to uncompleted an item after the sync. They found many duplicates items in the list!! which one should they uncomplete?

One way to achieve sync is to get all taks from all task-list then establish a relationship, and then start syncing.....but even then it's a problem...... 
```py
    def _fetch_all_tasks(self, tasklist_id, completed=False):
        """
        Fetches all the tasks & sets self.tasks
        """
        if completed:
            api_call = "getAllCompletedItems"
        else:
            api_call = "getUncompletedItems"
        url = self.BASE_URL + api_call
        params = {
            "token": self.token,
            "project_id": tasklist_id
            }
        req = requests.get(url, params = params)
        if req.status_code == 200:
            return json.loads(req.text)
```
As you can see **getAllCompletedItems** will fail for non premium users.

**Comment by PotHix** [comment]
Hi @khurshid-alam, it's been almost 8 months since the last interaction on this issue. 

I don't know if you still need help on this. I will close this issue but **please reopen in case you still need a workaround for it**, so we can check what can be done together. :+1:

**Comment by khurshid-alam** [comment]
I can't reopen this issue. So I am opening a new issue.
