### ISSUE TITLE
Plaese provide machine-readable example json files/specifications

### ISSUE THREAD

**Issue by dmitrij-drandarov** [Doist/todoist-api#21]
I'd really like to automatically read the most up-to-date json example or properties specification with a script for source generation. However the example and specification is embedded inside the markdown files and the formatting could change at any time. Is there a way to get machine-readable json examples or properties specification?

Best regards
Dmitrij :)

**Comment by imankulov** [comment]
Hi @dmitrij-drandarov 

We don't have a machine-readable API specification and don't have plans to add it soon. This approach could be useful for large APIs with thousands of endpoints, such as for Google APIs (and that's actually what they provide), but we don't think our API is large enough to justify the need and efforts for doing that.
