### ISSUE TITLE
`date_string` and `due_date_utc`

### ISSUE THREAD

**Issue by guillaumepotier** [Doist/todoist-api#25]
Hi there,

I have a question about [item creation](https://developer.todoist.com/#add-an-item) regarding these two dates.

If I understand well, `date_string` allows to specify task dates (with recurrence and other features) in a specific syntax (ie `10/5 @ 10`).

What is the purpose of `due_date_utc`. When specifying it, `date_string` is mandatory right?

My problem is that I have timezone issues with only `date_string`. In my app, I know the date in UTC format, not necessarily the end user timezone. If I only use `date_string` it would show the user a wrong date in utc. But when I specify `due_date_utc`, it seems to change nothing..

Am I missing something here?

Thanks

**Comment by lefcha** [comment]
(This is also answered on https://todoist.zendesk.com/agent/tickets/118360)

First, the 2 fields serve a different purpose, as `date_string` support recurring tasks, while the `due_date_utc` specifies not only the due date in UTC, but also the next due date for recurring tasks.

Now, if the task the user wants to create is not recurring, the user could set the `due_date_utc` to the date and time in UTC, eg. `2017-2-28T17:00`, while for the `date_string` (which is mandatory) the user could set it just to the date like `Feb 24`, it doesn't matter as long as the `due_date_utc` is set, that will be finally used.

**Comment by PotHix** [comment]
I'm closing this one since @lefcha already answered and we have a :+1: from @guillaumepotier. Please reopen in case something is not clear yet.
