### ISSUE TITLE
Add examples of getting items, projects, and using queries

### ISSUE THREAD

**Issue by pawelniewie** [Doist/todoist-api#26]
Seriously, why don't you list examples of getting items?

I just imported a bunch of tasks from a CSV file and they are garbage, would love to list them and remove them but hey, your documentation sucks.

Google reveals there's /v7/queries endpoint but can't make it work and no good example around.

**Comment by PotHix** [comment]
Hi @pawelniewie, we're working on it. :)

For now, we added a [Getting started section](https://developer.todoist.com/#getting-started) and we're working on improving the examples to make it easier.

We will also have a simpler API soon. I'm closing this issue but keep an eye on our documentation and feel free to open a new one or reopen this in case you need something.

**Comment by wwboynton** [comment]
Just want to chime in to add that this is still garbage...seriously, it's been over a year and your docs still have no example of how to list tasks in the "Getting Started" section? That's absurd. Am I missing something?

That combined with the deprecation of the `query` functionality makes todoist unkindly difficult to use as a developer. I wouldn't even really need documentation of how to list tasks if you gave me the ability to search them the same way I do in the UI...but instead, I'm expected to pull down every task myself and then filter them client side, and there's not any easily-accessible documentation on how to do that that I can find.

What's going on?

**Comment by PotHix** [comment]
@wwboynton yes, you can get that via the `sync` endpoint. The getting started uses the example of retrieving projects, maybe we should change that to items to make things clear.
