### ISSUE TITLE
Attempt to Import Templates Gives 403 FORBIDDEN

### ISSUE THREAD

**Issue by smittym** [Doist/todoist-api#28]
I am testing the import templates feature using Postman before I bother writing anything. When I try this URL

https://todoist.com/API/v7/templates/import_into_project?token=<MY_TOKEN>&project_id=<EXISTING_PROJECT_ID>&file=<MY_FILE>

I get a 403 FORBIDDEN error. If I take off the project_id, then I get an "Argument Missing" 400 error. So, it seems like the authorization is OK, but I can't import the template. Any ideas?

**Comment by smittym** [comment]
Never mind. Stupid mistake. Using GET instead of POST. Now I get a {status ok}, but the template is not being imported.

**Comment by PotHix** [comment]
Hi @smittym, did you managed to get your template imported? We can work on that in case you are still having problems.

**Comment by PotHix** [comment]
I'm closing this issue, feel free to reopen in case you still need help. :)
