### ISSUE TITLE
API: Item_Update: Could not update item by date_string since 18th June (v7)

### ISSUE THREAD

**Issue by khurshid-alam** [Doist/todoist-api#31]
Using my own developer token I could not update an item using `date_string` parameter.

Example code

```sh
curl https://todoist.com/API/v7/sync -d token=4y7844a80xxxxxxx -d commands='[{"type": "item_update",  "uuid": "d333d612-dafa-4aa0-89da-1f5b704fd382", "args": {"id": "224564491", "date_string" : "22 jun"}}]'
```

In response I am getting ok response but it doesn't actually update the item.

`{"sync_status":{"d00dd8b2-3698-466b-bxxxxxxxxxxx":"ok"},"temp_id_mapping":{},"full_sync":true,"sync_token":"Vr3TA0hC1YxxxxxxxxxxxY"}`

But if pull that particular task through query from api I can see that **the value of date_string is changing but it doesn't have any effect**.

What is going on?

**Comment by dddesign** [comment]
any news an this? my webapp using todoist-api use this function to reorganise tasks, so it's not working right now...

**Comment by PotHix** [comment]
I'm researching on this. We will have an answer soon. :)

**Comment by PotHix** [comment]
The bug was reproduced and we're working on a fix or workaround for it. I will post a new comment as soon as we have something.

**Comment by PotHix** [comment]
It was a regression, we fixed it and added more tests to avoid problems next time. 
I'm closing this issue now, please report in case you still find something odd.

**Comment by khurshid-alam** [comment]
Thanks. It is working now.
