### ISSUE TITLE
Property 'is_recurring' appears only in some recurring tasks

### ISSUE THREAD

**Issue by alexandrosio** [Doist/todoist-api#33]
Dear doist team,

In some recurring tasks, there exists a property **'is_recurring'** which is **always set to 0**; even though the task is recurring, its value is set to false; and, if a new recurring task is created, the 'is_recurring' property does not exist, which seems odd.

Documentation about the **'is_recurring'** property is nowhere to be found in the docs. Could you please clarify on how to go about using it?

Best,
Alexandros

**Comment by PotHix** [comment]
Hi @alexandrosio,

`is_recurring` is an internal attribute and should not be exposed as it is, this is the main reason why we have zero documentation on it. It will be removed soon, so we recommend to not rely on it.

In case you're searching how to deal with recurring tasks. Just complete them using [close-item](https://developer.todoist.com/#close-item). :)

**Comment by scholer** [comment]
So how can one reliably determine if a task is recurring with the v7.0 Sync API?

I can see that the current v7.1 Sync API (https://todoist.com/API/v7.1/sync) still has a `is_recurring` attribute in the `due` dict, even for new tasks.

Also, will Doist be officially documenting the v7.1 API at some point, and maybe upgrading the python docs to use it?

**Comment by PotHix** [comment]
Hi @scholer 

We are working on a new version of the API and `is_recurring` will probably be part of it, this is why we did not remove it yet. [Stay tuned for the news](https://twitter.com/doistdevs), we will release more info on that as soon as we release it.
