### ISSUE TITLE
Specify sync token for incremental syncing using the Python library

### ISSUE THREAD

**Issue by alexandrosio** [Doist/todoist-api#40]
I'm looking for a way to specify the `sync_token` used by the Python library of Todoist, in order to receive the resources updated since the `sync_token` specified; this would be beneficial in making my application recover from failures that may occur on the other end of the integration (syncing two services together). So far, I've thought of saving the resources that have not been acted upon in a database, but this does not seem to be an elegant solution. 

In your API Documentation the following example is supplied:
```
# Retrieved from: https://developer.todoist.com/sync/v7/?shell#read-resources

$ curl https://todoist.com/api/v7/sync \
    -d token=0123456789abcdef0123456789abcdef01234567 \
    -d sync_token='*' \
    -d resource_types='["all"]'
```

How can this be achieved using the Python library?

Regards,
Alexandros

**Comment by PotHix** [comment]
The python library already uses the sync token out of the box. When you run a query again it's using the cached Sync token.

Please refer to my example posted on [this issue](https://github.com/Doist/todoist-api/issues/35).

**Comment by alexandrosio** [comment]
Thanks for the prompt reply.

I have a sync_token stored in the database of my application; that token was retrieved using a previous synchronization done by using the api.sync() function of your API; Now, I would like to supply that token to the api.sync() function as a parameter, to overwrite the one stored in cache and perform a sync.

Something along the lines of:
`api.sync('previous_sync_token_from_my_db') `

If that is not possible, how can I change the cached sync_token used by the library?

What you've provided in #35, does not help in any way.

Thank you very much.

**Comment by PotHix** [comment]
Hi @alexandrosio,

We removed the complexity of managing the sync token some time ago. The Python library does that for you by default so you don't have to store the sync token and handle it yourself.

We recommend you to not store the sync token and just use sync for all activities. For the case you mentioned where you already have a sync token, just do a full sync (removing the cache) and let the library handle the next `sync`s for you.

**Comment by alexandrosio** [comment]
@PotHix, thank you for you help. You may close this issue :).
