### ISSUE TITLE
api.sync() returns HTML code for Bad Gateway

### ISSUE THREAD

**Issue by alexandrosio** [Doist/todoist-api#41]
I'm building a project that syncs a service with Todoist; thus, I have to call the `api.sync()` function every 2 seconds or so, taking into account the maximum number of 50 sync requests per minute, to keep the services in sync. Further, by reading your API Documentation, I've assumed the function returns JSON objects only; yet, the result of the `api.sync()` function has returned, on numerous occasions, the HTML code for Error 502 (Bad Gateway).

Please find attached the HTML document below:
[todoist_api_sync_response_error.txt](https://github.com/Doist/todoist-api/files/1261998/todoist_api_sync_response_error.txt)

Regards,
Alexandros

**Comment by PotHix** [comment]
Hi @alexandrosio,

The HTML is the default action when the API is somehow unavailable (HTTP status code >= 500). For these cases, the Python library should raise an exception for the application using it, which is not happening at the moment.

Please open an issue (or PR, it's up to you) for [todoist-python project](https://github.com/Doist/todoist-python) about that. :)
