### ISSUE TITLE
Changing projects from Inbox to another project

### ISSUE THREAD

**Issue by gezbo** [Doist/todoist-api#43]
Hello,

I'm trying to use the Developer API to update tasks in the inbox so that they move to one of my other projects.  I am able to change the values for other fields such as content and due date but changing the value for project_id does not work - am I doing something wrong or is this not possible?

Thanks

Gez

**Comment by PotHix** [comment]
You should use [move item](https://developer.todoist.com/sync/v7/#move-an-item) for that. :)

**Comment by gezbo** [comment]
Is that available on the REST API? Sorry for the noob questioning?

**Comment by PotHix** [comment]
It's not noob at all, you spotted that our documentation is missing some information. At the moment (it's still in beta) the REST API doesn't support moving tasks between projects. Just added to the documentation that the project_id is read-only for now. Thanks!

**Comment by gezbo** [comment]
No problem,

I thought I might be missing something. I guess I'll have to use v7 for the
moving aspect.

Thanks

Gez

**Comment by gezbo** [comment]
Also, in the python example for move item (I think it appears in other
places too), the lines below need to be updated to include the underlined...

>>> *item = *api.items.get_by_id(33548400)>>> item.move(128501607)


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by PotHix** [comment]
Fixed. Thanks!
