### ISSUE TITLE
Retrieving closed tasks

### ISSUE THREAD

**Issue by Critter** [Doist/todoist-api#44]
Hey.

Based on the documentation to get a task:
https://beta.todoist.com/API/v8/tasks/1234?token=$token

but that will only retrieve a task that is open. How can I get a task that is completed?

I'm using zapier.com to trigger when a task is completed. I'm grabbing the task_id and passing it to my server to extract the comments, etc.. but when I try to pull up information about the task using the above endpoint, I get `file not found`. If I re-open the task and hit the endpoint again... I get the expected information.

Shouldn't that call return a task regardless with the `completed` property set to `true` or `false`?

**Comment by PotHix** [comment]
Hi, @Critter! 

It's part of the limitations for free users. [Complete tasks retrieval is only available for premium users](https://developer.todoist.com/sync/v7/#get-all-completed-items) and it holds for the REST API as well.

**Comment by Critter** [comment]
I have a premium account. So what you are saying is it /should/ be returning for me?

**Comment by PotHix** [comment]
Thanks for the additional information, @Critter! It should be returning the task details for this case, so I'm reopening this issue and adding an internal task for further investigation.

Thanks for reporting. :+1:

**Comment by PotHix** [comment]
Did some research and it's not implemented in our current beta release we will plan that for the stable release. No ETA for now.

I would recommend you to use the [Sync API](https://developer.todoist.com/sync/v7/) if you need this data.

**Comment by Critter** [comment]
Thanks for looking into it. I'll have a gander at the sync.

I'm just glad to know I'm not losing it.
