### ISSUE TITLE
When adding a new task using python, get raise ValueError("No JSON object could be decoded") error

### ISSUE THREAD

**Issue by ocopaul** [Doist/todoist-api#45]
json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")

Using:

import uuid, requests, json
requests.post("https://beta.todoist.com/API/v8/tasks",
    params={"token": token},
    data=json.dumps({"content": "Appointment with Maria",
                     "due_string": "tomorrow at 12:00",
                     "due_lang": "en",
                     "priority": 4}),
    headers={
        "Content-Type": "application/json",
        "X-Request-Id": str(uuid.uuid4()),
    }
).json()

**Comment by PotHix** [comment]
Thanks for reporting, it's a regression. We identified the problem and will deploy a correction at the beginning of the next week.

**Comment by PotHix** [comment]
We just released a small patch and it should be working again. Sorry for the inconvenience.
