### ISSUE TITLE
Todoist google calendar integration.

### ISSUE THREAD

**Issue by mesqueeb** [Doist/todoist-api#52]
Dear Todoist.
I think your integration of google calendar is just fantastic.
I wonder, which information do you store in your todoist user data to keep the connection to google calendar? I think you would save some kind of refresh token of the google calendar api, is that correct?

I have a similar app but every time the user logs in (or opens the account on a separate device) he needs to reconnect (re-auth to gapi) the google calendar.
I'm not sure how Todoist was able to link google calendar to the todoist account forever.

Any advice much appreciated. : )

**Comment by alexandrosio** [comment]
[This](https://github.com/alexandrosio/todoist-gcal-sync) may help :).

**Comment by imankulov** [comment]
Hi @mesqueeb,

In order to avoid re-authentication, you should consider asking permission for so-called offline access to user's data: [ref](https://developers.google.com/identity/protocols/OAuth2WebServer#offline), and in turn you'll get a refresh token indeed.
