### ISSUE TITLE
Time when item was checked and other fields

### ISSUE THREAD

**Issue by Kaleidophon** [Doist/todoist-api#53]
Hi Doist team, quick question about the API for which I couldn't find a satisfying answer in your doc:

1. Is there a way to retrieve *all* the items (including closed ones) of a project via the API?
2. Is there a field displaying when this item has been checked?
3. Is there a field telling me whether this item has been postponed?

Thanks a lot!

**Comment by PaulHalliday** [comment]
You can get all items from `state` or `items.all()`. 

When items have been checked, they will have a checked property which returns `0` or `1` depending on their status. There isn't a time associated with this property.

This could then be filtered to find _only checked_ items:

```python
def is_checked(item): return item['checked'] == 1

items = list(filter(is_checked, api.state['items']))
```
There doesn't appear to be a field supported for postponed items as of yet.

**Comment by Kaleidophon** [comment]
Thanks for the response!
