### ISSUE TITLE
Cant't run CURL doc example

### ISSUE THREAD

**Issue by RareScrap** [Doist/todoist-api#55]
Hello, I'm trying to get started with Todoist Api, but cant'r run even first command.

I followed this instruction (https://developer.todoist.com/sync/v7/#get-all-projects)

I try run this command:
curl -k https://todoist.com/api/v7/sync -d token=MY_TOKEN -d sync_token='*' -d resource_types='["projects"]'
but everytime i get:
{"error_tag":"INVALID_ARGUMENT_VALUE","error_code":20,"http_code":400,"error_extra":{"expected":"list","argument":"resource_types"},"error":"Invalid argument value"}

Google doesn't help. What I do wrong?

**Comment by rohitpaulk** [comment]
@RareScrap I tried copying the command you pasted, and also tried copying it directly from the docs - both worked. Screenshots:

**Command copied from issue description**:
![screen shot 2018-04-09 at 12 21 52 am](https://user-images.githubusercontent.com/3893573/38471274-607bb5f8-3b8c-11e8-8da1-134eb5ec86c9.png)

**Command copied from docs**:

![screen shot 2018-04-09 at 12 22 48 am](https://user-images.githubusercontent.com/3893573/38471275-60abf420-3b8c-11e8-8972-ac2a1fd72314.png)

Is it possible that something weird is happening with your shell?

**Comment by RareScrap** [comment]
@rohitpaulk Thank you. Most likely, you are right. I'll try another shell

**Comment by PaulHalliday** [comment]
I can confirm this works as intended. Can you try typing the command out on one line instead of copy pasting? :)

**Comment by PaulHalliday** [comment]
Are you copying the command into Notes for macOS? It seems to change the formatting of the cURL example and replaces the speech mark/apostrophe for different unicodes:

”’ vs "'

When I did this, I got the same INVALID_ARGUMENT example due to the above issue.
