### ISSUE TITLE
Unable to authenticate for user information

### ISSUE THREAD

**Issue by maurice-schleussinger** [Doist/todoist-api#58]
I want to use the user object and authenticate via OAuth like so:
`https://todoist.com/oauth/authorize?client_id=__SECRET__&scope=data:read_write&state=secret`

**Problem:**
The user authenticates (and the authentication page states access to user data is granted to my application). However, user information is empty: `user: {}`.

**Possible Solution:**
Either add user data to read_write scope or add a scope specifically for the user information.

**Comment by PotHix** [comment]
Just tried the same process and it works as expected. I can get the user object after the user authorizes to use his data and I get the access_token.

This request returns the user object:

```
curl -s https://todoist.com/api/v7/sync -d token=__SECRET__ -d sync_token='*' -d resource_types='["user"]'
```

Hope it helps. We will be closing this repository so we can use some internal processes on our documentation source, but if you still need help with that you can always [contact us via support](https://get.todoist.help/hc/en-us/requests/new) and your request will reach our developers. :+1:
