### ISSUE TITLE
How do I get all closed tasks? Premium user, Rest v8

### ISSUE THREAD

**Issue by kaushalmodi** [Doist/todoist-api#60]
Hello,

In order to reopen a task, I need the task ID. 

But to get the ID of a closed task, I need to first retrieve all the closed tasks. 

- I am a premium user
- Using REST v8

**Comment by tworogue** [comment]
It seems to me that this feature is only available when making use of Sync API so far.
See here: https://developer.todoist.com/sync/v7/#get-all-completed-items

**Comment by kaushalmodi** [comment]
Yes, I am aware of this feature availability on Sync API. 

This was more of a feature request to add that to the REST API too.

**Comment by PotHix** [comment]
@kaushalmodi it's indeed only available in the Sync API. The REST API is still in beta state but your feedback is already in our list. 

We will be closing this repository so we can better organize our docs, but you can always [contact us via support](https://get.todoist.help/hc/en-us/requests/new) and your request will reach our developers. :+1:
