### ISSUE TITLE
Public Test-Endpoint?

### ISSUE THREAD

**Issue by 6uhrmittag** [Doist/todoist-api#63]
Hi!

I‘m just wondering if there is any public test endpoint available that I overlooked?

My application([taskbutler](https://github.com/6uhrmittag/taskbutler)) is tiny, but requires premium and it would be much easier to test with a real endpoint rather than using the cache-file or my personal account(which I don‘t want to use during CI/CD).

Many thanks and keep up the great work!

**Comment by PotHix** [comment]
Hi @6uhrmittag! Thanks for doing such a nice project! :)

Unfortunately, we don't have a test endpoint, you will have to use a dummy account for that.

We will be closing this repository so we can better organize our docs, but you can always [contact us via support](https://get.todoist.help/hc/en-us/requests/new) and your request will reach our developers.
